### ISSUE TITLE
USSD simulator errors

### ISSUE THREAD

**Issue by qodehub-nanadjei** [hubtel/ussd-mocker#2]
I recently downloaded your simulator from https://github.com/hubtel/ussd-mocker
Everything worked out with running it but getting some errors from it whiles waiting for a response from the app. The error is as follows---
TypeError: Cannot read property 'substr' of undefined
at session (..\ussd-mocker-master\app\controllers\index.js:33:6)
at Layer.handle [as handle_request] (..\ussd-mocker-master\node_modules\express\lib\router\layer.js:82:5)
at next (..\ussd-mocker-master\node_modules\express\lib\router\route.js:110:13)
at Route.dispatch (..\ussd-mocker-master\node_modules\express\lib\router\route.js:91:3)
at Layer.handle [as handle_request] (..\ussd-mocker-master\node_modules\express\lib\router\layer.js:82:5)
at ..\ussd-mocker-master\node_modules\express\lib\router\index.js:267:22
at Function.proto.process_params (..\ussd-mocker-master\node_modules\express\lib\router\index.js:321:12)
at next (..\ussd-mocker-master\node_modules\express\lib\router\index.js:261:10)
at Function.proto.handle (..\ussd-mocker-master\node_modules\express\lib\router\index.js:166:3)
at router (..\ussd-mocker-master\node_modules\express\lib\router\index.js:35:12)
at Layer.handle [as handle_request] (..\ussd-mocker-master\node_modules\express\lib\router\layer.js:82:5)
at trim_prefix (..\ussd-mocker-master\node_modules\express\lib\router\index.js:302:13)
at ..\ussd-mocker-master\node_modules\express\lib\router\index.js:270:7
at Function.proto.process_params (..\ussd-mocker-master\node_modules\express\lib\router\index.js:321:12)
at next (..\ussd-mocker-master\node_modules\express\lib\router\index.js:261:10)
at jsonParser (..\ussd-mocker-master\node_modules\body-parser\lib\types\json.js:96:40)

**Comment by quenginedev** [comment]
I am currently experiencing the same error too especially when I run an async function and I return the response from the function.
eg. 
`function(req, res){
    return asyncFunction().then(function(){
        return {
            ....
            return { Type: "Response", Message: "..."}
        }
    })
}`
